name: Auto Release Action
on:
  push:
    branches:
    - 'dev'
  pull_request:
    branches:
    - 'dev'

env:
  RCVersion: < 0.0.0 PreRelease 0>
  isPreRelease: true
  Version: Init
  CommitMessage: Init

jobs:
  Build_Application:
    name: Build Application
    runs-on: windows-2025
    steps:
      - name: CheckOut Repo
        uses: actions/checkout@v4

      - name: Cache and Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.5'
          cache: 'pip' # caching pip dependencies

      - name: Install requirements
        run: pip3 install -r ./requirements.txt

      - name: Create Build Variable
        run: |
          $ErrorActionPreference = 'Stop'
          $isPreRelease = python -c "import Version;print(Version.isPreRelease)";
          $isPreReleaseBool = [bool]::Parse($isPreRelease);
          if ($isPreReleaseBool) {
              $version = python -c "import Version; print(Version.preVersion)";
              $rcVersion = $version -replace "pre", " PreRelease ";
          } else {
              $version = python -c "import Version; print(Version.version)";
              $rcVersion = $version;
          }
          echo "v:'${version}',rcv:'${rcVersion}'";
          echo "isPreRelease=${isPreReleaseBool}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append;
          echo "Version=${version}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append;
          echo "RCVersion=< ${rcVersion} >" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append;

      - name: Build ${{ env.Version }}
        run: |
          $vc = "${{ github.event.head_commit.message }}" -split "  ";
          echo "$vc";
          echo "CommitMessage=$($vc[1])" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append;
          powershell.exe ./buildLauncher.ps1;


      # 上传构建产物
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          name: ${{ env.RCVersion }}  ${{ env.CommitMessage }}  < Auto Release >
          tag_name: ${{ env.Version }}
          draft: false
          body_path: ${{ github.workspace }}/changelog.md
          prerelease: ${{ env.isPreRelease }}
          files: ./MusyncSaveDecode/Archive/*
          retention-days: 15          # 可选：保留天数（默认 90 天）

