name: Auto Release Build Action
on:
  push:
    branches:
    - 'main'

env:
  RCVersion: < 0.0.0 PreRelease 0>
  isPreRelease: true
  Version: Init

jobs:
  Build_Release_Application:
    name: Build Release Application
    runs-on: windows-2025
    steps:
      - name: CheckOut Repo
        uses: actions/checkout@v4

      - name: Cache and Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.5'
          cache: 'pip' # caching pip dependencies

      - name: Install requirements
        run: pip3 install -r ./requirements.txt

      - name: Create Build Variable
        run: |
          $ErrorActionPreference = 'Stop'
          $isPreRelease = python -c "import Version;print(Version.isPreRelease)";
          $isPreReleaseBool = [bool]::Parse($isPreRelease);
          if ($isPreReleaseBool) {
              $version = python -c "import Version; print(Version.preVersion)";
              $rcVersion = $version -replace "pre", " PreRelease ";
          } else {
              $version = python -c "import Version; print(Version.version)";
              $rcVersion = $version + "Release";
          }
          echo "v:'${version}',rcv:'${rcVersion}'";
          echo "isPreRelease=${isPreReleaseBool}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append;
          echo "Version=${version}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append;
          echo "RCVersion=< ${rcVersion} >" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append;

      - name: Build ${{ env.Version }}
        run: |
          powershell.exe ./buildLauncher.ps1;

      - name: Commit Build File
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          name: ${{ env.RCVersion }}  ${{ github.event.head_commit.message }}  < Auto Release >
          tag_name: ${{ env.Version }}
          draft: false
          body_path: ${{ github.workspace }}/changelog.md
          prerelease: ${{ env.isPreRelease }}
          files: ./MusyncSaveDecode/Archive/*
